// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2xlrVPBhsgT_r-kqCkb-phPbOlmBECQ',
    appId: '1:944863011897:web:f7c5f7af8ecd86998e19e8',
    messagingSenderId: '944863011897',
    projectId: 'flash-chat-9502f',
    authDomain: 'flash-chat-9502f.firebaseapp.com',
    storageBucket: 'flash-chat-9502f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnCvCxLZB2Dy1upTa9X_ZQGG7wf2Q1Uvs',
    appId: '1:944863011897:android:497e079e311867e38e19e8',
    messagingSenderId: '944863011897',
    projectId: 'flash-chat-9502f',
    storageBucket: 'flash-chat-9502f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MkVee5Yow6pEoQ6HSGXlx-YtK_xjJ_4',
    appId: '1:944863011897:ios:4f52adcc0da80f458e19e8',
    messagingSenderId: '944863011897',
    projectId: 'flash-chat-9502f',
    storageBucket: 'flash-chat-9502f.appspot.com',
    iosBundleId: 'com.example.flash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_MkVee5Yow6pEoQ6HSGXlx-YtK_xjJ_4',
    appId: '1:944863011897:ios:49326041c06f5e8f8e19e8',
    messagingSenderId: '944863011897',
    projectId: 'flash-chat-9502f',
    storageBucket: 'flash-chat-9502f.appspot.com',
    iosBundleId: 'com.example.flash.RunnerTests',
  );
}
